spring:
  profiles:
    active: local
  application:
    name: availability-service
  datasource:
    url: jdbc:postgresql://localhost:5433/availability_db
    username: myagenda
    password: myagenda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: clave-super-secreta-12345678901234567890

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always
