services:


  users-db:
    image: postgres:16-bookworm
    container_name: users-db

    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5438:5432"

    volumes:
      - users_pg_data:/var/lib/postgresql/data

  login-db:
    image: postgres:16-bookworm
    container_name: login-db

    environment:
      POSTGRES_DB: login_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5440:5432"

    volumes:
      - login_pg_data:/var/lib/postgresql/data


  authorization-db:
    image: postgres:16-bookworm
    container_name: authorization-db

    environment:
      POSTGRES_DB: authorization_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5441:5432"

    volumes:
      - authorization_pg_data:/var/lib/postgresql/data


  identity-validation-db:
    image: postgres:16-bookworm
    container_name: identity-validation-db

    environment:
      POSTGRES_DB: identity_validation_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5442:5432"

    volumes:
      - identity_validation_pg_data:/var/lib/postgresql/data

  onboarding-db:
    image: postgres:16-bookworm
    container_name: onboarding-db

    environment:
      POSTGRES_DB: onboarding_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5443:5432"

    volumes:
      - onboarding_pg_data:/var/lib/postgresql/data

  fraud-guardian-db:
    image: postgres:16-bookworm
    container_name: fraud-guardian-db

    environment:
      POSTGRES_DB: fraud_guardian_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5444:5432"

    volumes:
      - fraud_guardian_pg_data:/var/lib/postgresql/data


  audit-logging-db:
    image: postgres:16-bookworm
    container_name: audit-logging-db

    environment:
      POSTGRES_DB: audit_logging_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5445:5432"

    volumes:
      - audit_logging_pg_data:/var/lib/postgresql/data

#  identity-db:
#    image: postgres:16-bookworm
#    container_name: identity-db
#
#    environment:
#      POSTGRES_DB: identity_db
#      POSTGRES_USER: myagenda
#      POSTGRES_PASSWORD: myagenda
#
#    ports:
#      - "5432:5432"
#
#    volumes:
#      - identity_pg_data:/var/lib/postgresql/data

  availability-db:
    image: postgres:16-bookworm
    container_name: availability-db

    environment:
      POSTGRES_DB: availability_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5433:5432"

    volumes:
      - availability_pg_data:/var/lib/postgresql/data

  booking-db:
    image: postgres:16-bookworm
    container_name: booking-db

    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5436:5432"

    volumes:
      - booking_pg_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16-bookworm
    container_name: payment-db

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5434:5432"

    volumes:
      - payment_pg_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16-bookworm
    container_name: notification-db

    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5435:5432"

    volumes:
      - notification_pg_data:/var/lib/postgresql/data

  wallets-db:
    image: postgres:16-bookworm
    container_name: wallets-db

    environment:
      POSTGRES_DB: wallets_db
      POSTGRES_USER: myagenda
      POSTGRES_PASSWORD: myagenda

    ports:
      - "5437:5432"

    volumes:
      - wallets_pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: myagenda
      MONGO_INITDB_ROOT_PASSWORD: myagenda

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  users_pg_data:
  login_pg_data:
  authorization_pg_data:
  identity_validation_pg_data:
  onboarding_pg_data:
  fraud_guardian_pg_data:
  audit_logging_pg_data:
#  identity_pg_data:
  availability_pg_data:
  booking_pg_data:
  payment_pg_data:
  notification_pg_data:
  wallets_pg_data:
  mongodb_data: