spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/identity_validation_db
    username: myagenda
    password: myagenda

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false