spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: identity-route
          uri: http://localhost:8081
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus